services:
  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: skillbridge-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      # Neon PostgreSQL configuration
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${PGUSER}
      SPRING_DATASOURCE_PASSWORD: ${PGPASSWORD}

      # JPA configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      SPRING_JPA_FORMAT_SQL: ${SPRING_JPA_FORMAT_SQL}

      # Server configuration
      SERVER_PORT: ${SERVER_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      # CORS configuration
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    networks:
      - skillbridge-network

  # Next.js Frontend
  frontend:
    build:
      context: ./skillbridge-frontend
      dockerfile: Dockerfile
    container_name: skillbridge-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      # Backend API URL
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NODE_ENV: ${NODE_ENV}
    networks:
      - skillbridge-network

networks:
  skillbridge-network:
    driver: bridge
